"""
Application i18n.

Use:
    from i18n import t

    t("attendance")
    t("employee_name")

Change language:
    from i18n import set_language

    set_language("ar")
    set_language("en")
"""

LANGUAGES = {
    "ar": {

        # ==========================
        # Report
        # ==========================

        "attendance_report": "تقرير الحضور",

        # ==========================
        # Sections
        # ==========================

        "employee_information": "بيانات الموظف",
        "attendance": "الحضور",
        "summary": "الملخص",

        # ==========================
        # Employee
        # ==========================

        "employee_name": "اسم الموظف",
        "employee_id": "رقم الموظف",
        "shift": "الشيفت",
        "position": "الوظيفة",

        # ==========================
        # Attendance Table
        # ==========================

        "date": "التاريخ",
        "weekday": "اليوم",
        "check_in": "الحضور",
        "check_out": "الانصراف",
        "worked": "ساعات العمل",
        "late": "التأخير",
        "early_leave": "الانصراف المبكر",
        "overtime": "العمل الإضافي",
        "status": "الحالة",

        # ==========================
        # Attendance Status
        # ==========================

        "present": "حاضر",
        "late_status": "متأخر",
        "absent": "غائب",
        "holiday": "إجازة",

        # ==========================
        # Summary
        # ==========================

        "present_days": "أيام الحضور",
        "late_days": "أيام التأخير",
        "absent_days": "أيام الغياب",

        "worked_time": "إجمالي ساعات العمل",
        "late_time": "إجمالي التأخير",
        "early_leave_time": "إجمالي الانصراف المبكر",
        "overtime_time": "إجمالي العمل الإضافي",

        "average_check_in": "متوسط وقت الحضور",
        "average_check_out": "متوسط وقت الانصراف",

        # ==========================
        # Footer
        # ==========================

        "generated_by": "تم إنشاء التقرير بواسطة Royal Reports",

        # ==========================
        # UI
        # ==========================

        "browse": "استعراض",
        "generate": "إنشاء التقارير",
        "settings": "الإعدادات",

        "select_excel": "اختر تقرير Excel",
        "finished": "اكتمل",
        "error": "خطأ",

        "done_successfully": "تم إنشاء التقارير بنجاح",

        "employees": "عدد الموظفين",
        "output_folder": "مجلد الحفظ",

        # ==========================
        # Settings
        # ==========================

        "company_name": "اسم الشركة",
        "report_title": "عنوان التقرير",

        "language": "اللغة",

        "work_schedule": "مواعيد العمل",

        "shift_start": "بداية الدوام",
        "shift_end": "نهاية الدوام",

        "late_grace": "سماحية التأخير",

        "save": "حفظ",
        "cancel": "إلغاء",

        "open_folder_after_finish": "فتح مجلد النتائج بعد الانتهاء",
    },

    "en": {

        # ==========================
        # Report
        # ==========================

        "attendance_report": "Attendance Report",

        # ==========================
        # Sections
        # ==========================

        "employee_information": "Employee Information",
        "attendance": "Attendance",
        "summary": "Summary",

        # ==========================
        # Employee
        # ==========================

        "employee_name": "Employee Name",
        "employee_id": "Employee ID",
        "shift": "Shift",
        "position": "Position",

        # ==========================
        # Attendance Table
        # ==========================

        "date": "Date",
        "weekday": "Weekday",
        "check_in": "Check In",
        "check_out": "Check Out",
        "worked": "Worked Hours",
        "late": "Late",
        "early_leave": "Early Leave",
        "overtime": "Overtime",
        "status": "Status",

        # ==========================
        # Attendance Status
        # ==========================

        "present": "Present",
        "late_status": "Late",
        "absent": "Absent",
        "holiday": "Holiday",

        # ==========================
        # Summary
        # ==========================

        "present_days": "Present Days",
        "late_days": "Late Days",
        "absent_days": "Absent Days",

        "worked_time": "Worked Hours",
        "late_time": "Late Time",
        "early_leave_time": "Early Leave Time",
        "overtime_time": "Overtime Time",

        "average_check_in": "Average Check In",
        "average_check_out": "Average Check Out",

        # ==========================
        # Footer
        # ==========================

        "generated_by": "Generated by Royal Reports",

        # ==========================
        # UI
        # ==========================

        "browse": "Browse",
        "generate": "Generate Reports",
        "settings": "Settings",

        "select_excel": "Select Excel Report",
        "finished": "Finished",
        "error": "Error",

        "done_successfully": "Reports generated successfully",

        "employees": "Employees",
        "output_folder": "Output Folder",

        # ==========================
        # Settings
        # ==========================

        "company_name": "Company Name",
        "report_title": "Report Title",

        "language": "Language",

        "work_schedule": "Work Schedule",

        "shift_start": "Shift Start",
        "shift_end": "Shift End",

        "late_grace": "Late Grace",

        "save": "Save",
        "cancel": "Cancel",

        "open_folder_after_finish": "Open output folder after finish",
    },
}

_current_language = "ar"


def set_language(language: str) -> None:
    """
    Change application language.

    Parameters
    ----------
    language : str
        Language code ("ar", "en", ...)
    """

    global _current_language

    if language in LANGUAGES:
        _current_language = language


def get_language() -> str:
    """
    Return current language code.
    """

    return _current_language


def t(key: str) -> str:
    """
    Translate a key.

    If the key doesn't exist,
    the key itself is returned.
    """

    return LANGUAGES.get(
        _current_language,
        LANGUAGES["en"],
    ).get(key, key)

def is_rtl() -> bool:
    """
    Return True if current language is Right-To-Left.
    """

    return _current_language in {"ar"}