from reportlab.lib.pagesizes import A4

# Page
PAGE_WIDTH, PAGE_HEIGHT = A4
PAGE_MARGIN = 40

# Header
HEADER_TOP = 50
HEADER_SPACING = 25
HEADER_BOTTOM_SPACING = 20

# Sections
SECTION_SPACING = 35

# Employee Info
LABEL_VALUE_GAP = 110

# Table
TABLE_TOP_MARGIN = 30
TABLE_HEADER_HEIGHT = 24
TABLE_ROW_HEIGHT = 22
TABLE_CELL_PADDING = 6

# Footer
FOOTER_MARGIN = 30